version: "1.0"
services:
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    ports:
     - "9090:9090"
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    restart: always
